### ISSUE TITLE
_databaseLoaded

### ISSUE THREAD

**Issue by malhal** [Meteor-Community-Packages/ground-db#111]
When loading offline it would be good to know if the database has been loaded, so you don't need to wait indefinitely for subscriptionReady or Ground.ready() which by my understanding doesn't happen when offline. I saw the _databaseLoaded flag however I couldn't get it to work with a tracker I'm guessing because it isn't reactive. Would you please consider making it reactive or making a databaseLoaded callback. Thanks!

**Comment by raix** [comment]
What about `Ground.on('resumed');`?
https://github.com/GroundMeteor/db/blob/connection-driver/groundDB.client.js#L461

**Comment by malhal** [comment]
Thanks for your comment but I have no idea how to use that method, it doesn't appear to be documented. FYI I'm quite new to Meteor so not familiar with the patterns. Heres what I tried before giving up:

```javascript
Ground.on('resumed', function(){
	console.log("resumed");
});

Tracker.autorun(function () {
  var resumed = Ground.on('resumed');
  if(resumed){
	console.log("ground resumed");
  }
});

Ground.on('resumed') = function(){
	console.log("resumed");
};
```

**Comment by malhal** [comment]
Also tried

```javascript
	Ground.addListener('resumed', function() { 
		console.log("resumed");
		});
```
...to no avail.
Please could you update the readme with event examples cause really shooting in the dark here :-S

**Comment by raix** [comment]
```js
Ground.on('resumed') = function(evt){
    // expect { type: 'database', collection: 'foo' }
    console.log('resumed', evt);
};
```

**Comment by abcd-ca** [comment]
Hi @raix, Thanks for a great library. I'm trying to do the same thing I think and .on('resumed', fn) isn't doing anything for me. All I need to do is ensure that a couple of my collections have records before I navigate users to a view that depends on them and in one case do some data manipulation once the collection is loaded. When online, I use the syntax, 

```
Meteor.subscribe 'Messages',
    onReady: ->
        resolve()
    onStop: (err)->
        reject(err)
```

When starting my app offline, `onReady` never fires and my app hangs. I tried watching `Ground.ready()` but that only becomes true when I'm online. Does `Ground.ready()` actually mean it's done populating the offline, Ground database from the remotely loaded data (vs ready to use when offline)?

I'm not sure why Ground.on('resumed') doesn't fire (tested offline and online). What does resumed mean in the Ground context – resumed being able to work offline or network connectivity has been restored? On startup do I need to first check if device is offline and if so just call `Meteor.subscribe('Messages')` but if I'm starting up online use the above syntax with the `onReady` handler? I feel like I'm almost there and just need some clarity. Thank you!

**Comment by abcd-ca** [comment]
I have come up with the following suitable workaround, FYI. Essentially I wait until the collection has more than 0 items:
```
		getMessages = ->
			$q (resolve, reject)->
				Meteor.subscribe 'Messages'

				stop = $interval ->
					if Messages.find().count() > 0
						$interval.cancel(stop)
						resolve()
				, 100
```

**Comment by gerwinbrunner** [comment]
I created a pull request to add a new 'loaded' event which can be used to accomplish this.
https://github.com/GroundMeteor/db/pull/141
