### ISSUE TITLE
Ground is not defined

### ISSUE THREAD

**Issue by wmendes** [Meteor-Community-Packages/ground-db#113]
Im using telescope and after i add ground and change my Mongo.Collection to Ground.Collection i had this error on startup.

Im doing something wrong? Ground is not global?

**Comment by niketaB** [comment]
I am getting same error..
Please let me know if any body has resolved.

**Comment by pdiniz13** [comment]
Take a look at what version of GroundDb your running. I had the same issue and found out that the default version being installed is 0.0.9 which has the old deprecated global variable GroundDb as opposed to the new one Ground. You can switch the version you are using by adding ground:db@=0.3.14 to your package dependencies.
