### ISSUE TITLE
GroundDB with FlowRouter 

### ISSUE THREAD

**Issue by isAlmogK** [Meteor-Community-Packages/ground-db#127]
Any plans to support flow router?

**Comment by markoshust** [comment]
I believe `ground:db` is a collection/server package, and has nothing to do with routing. Correct?

**Comment by almogdesign** [comment]
Yes and no, there is the subscription part and I remember the new version had some implementation around iron router

**Comment by markoshust** [comment]
Ok, let me know what you find that is specific to iron... not sure what that would be exactly.

**Comment by StorytellerCZ** [comment]
Since we didn't hear back in a while, I'm closing this issue.
