### ISSUE TITLE
Constellation kills ground db

### ISSUE THREAD

**Issue by chmac** [Meteor-Community-Packages/ground-db#131]
When we install the `﻿babrahams:constellation` package, ground DB gets a broken error the same as #119. Not sure what the underlying cause is. We just removed that package for now and we're back in business...

**Comment by raix** [comment]
I've released `2.0.0-alpha.1` [Notes about the new version, migration and what it doesn't do](https://github.com/GroundMeteor/db/issues/153#issuecomment-206125703) - The issue might be resolved in that version, let me know what you think
