### ISSUE TITLE
Ground:db cause iron:router not working in Internet Explorer 10

### ISSUE THREAD

**Issue by wuzhuzhu** [Meteor-Community-Packages/ground-db#134]
When I added ground:db by "meteor add ground:db" and add a events collection into ground like this:
  Ground.Collection(events); 
It looks all right in localhost:3000, but when I deploy the codes into server by mup, my homepage turned into iron router error page and says I had not defined any route. And any of other routes broken.
Remove the package and ground collection line, deploy by same mup way will fix this.

**Comment by Meloncon** [comment]
I'm experiencing the same issue, as well. I get two errors in the console in IE10:

![ie10consoleerrors](https://cloud.githubusercontent.com/assets/583455/13714099/7c8f798e-e79a-11e5-9cbf-91283e877edb.png)

Unfortunately, it only throws this on production after it is mup deployed, so I don't get the "friendly" JavaScript line number it threw an error on. If there isn't already, an issue should probably be opened with @Raix (the error _did_ say he would work his butt off to fix it. :smile: ). The second error is simply stating "Router" is undefined.

If it is helpful for anyone, I can provide the minified line that the error says it occurred on too. Just let me know.

**Comment by raix** [comment]
bugger - what version of Meteor are you using?

**Comment by Meloncon** [comment]
I'm using METEOR@1.2.1 currently.

**Comment by raix** [comment]
I've released `2.0.0-alpha.1` [Notes about the new version, migration and what it doesn't do](https://github.com/GroundMeteor/db/issues/153#issuecomment-206125703) - The issue might be resolved in that version, let me know what you think
