### ISSUE TITLE
Get records from GroundDB with Limit keyword not working in Andriod/iOS app

### ISSUE THREAD

**Issue by mitiaptest** [Meteor-Community-Packages/ground-db#135]
We are facing problem to fetch the records from groundDB with limit and skip.

If we are going to use limit query its gives error "Match error: Failed Match.OneOf or Match.Optional validation" .

Also this is working on normal web environment but not in Android application.

Please help me on it.

Thanks,

**Comment by mitiaptest** [comment]
Can you guys please help me on this ?

**Comment by raix** [comment]
I've released `2.0.0-alpha.1` [Notes about the new version, migration and what it doesn't do](https://github.com/GroundMeteor/db/issues/153#issuecomment-206125703) - The issue might be resolved in that version, let me know what you think
