### ISSUE TITLE
Use with numtel:mysql

### ISSUE THREAD

**Issue by HamburgerJungeJr** [Meteor-Community-Packages/ground-db#145]
Hi,

can I use your project with the numtel:mysql package or is there a need for a meteor collection?

Greetings
HamburgerJungeJr

**Comment by raix** [comment]
You might be able to but probably not out of the box,

Btw. I've released `2.0.0-alpha.1` [Notes about the new version, migration and what it doesn't do](https://github.com/GroundMeteor/db/issues/153#issuecomment-206125703) - The issue might be resolved in that version, let me know what you think
