### ISSUE TITLE
go beyond localstorage limit

### ISSUE THREAD

**Issue by drgorb** [Meteor-Community-Packages/ground-db#18]
The limit for localstorage is 3MB which is not enough to store all the master data we have.

we would be willing to finance the development of a new version of ground-db that stores the data in another manner and allows unlimited data volumes

**Comment by btafel** [comment]
Hi @drgorb did you ever find a solution to this? Thanks

**Comment by paranoico** [comment]
Hello, GorundDB version 2.0.0 now works with IndexedDB or WebSQL since it is based on LocalForage.
IndexedDB is the newer option, but can be very slow. It has much more room that LocalStorage.

**Comment by raix** [comment]
*(I had actually added cordova support for native storage but it did not work consistently)*

**Comment by paranoico** [comment]
Hello @raix 
In our testing we have found that IndexedDB can take more than 5 minutes to give an answer in some cases, Native Storage should be a lot better than that.

**Comment by drgorb** [comment]
@btafel no I could never get it to work reliably. we ended up restricting access to the master data only in online mode
