### ISSUE TITLE
Stub functions problems in MantraJS or React

### ISSUE THREAD

**Issue by paranoico** [Meteor-Community-Packages/ground-db#189]
Hello again @raix,

We have found another issue for us using MantraJS:

- When have setup some stub functions.
- On those all functions we have referenced only GroundDB II collections. And everything works correctly when offline.
- But when Online, we get documents inserted twice, with different _id field. It seems that stub functions generated data is not erased.
- We are working now in some different paths to solve it:
  1. Creating an autorun to detect those duplicates and delete them.
  2. We are checking if using `Meteor.status().connected` can allow us to prevent stub action, but seems that it does not change immediately when connection is lost.

I have also found this https://groups.google.com/forum/#!topic/meteor-core/s3OLSWj7kvI and your package https://github.com/raix/stubfence but does not seem to solve our specific problem.

Is there anything else we could try?

Thanks in advance.

**Comment by raix** [comment]
are you using the latest ground db II ? (cause that doesn't use stubfence)

**Comment by paranoico** [comment]
Yes, using latest GroundDB II.

Seems to be a Meteor issue not preserving ID Consistent Generation and, in the other hand, similar to this: https://github.com/meteor/meteor/issues/1285

And GroundDB preserves the doubled data because the second document has another ID. So we have made a workaround creating our own documents IDs. So far seems to be working.

Thanks.

**Comment by StorytellerCZ** [comment]
Should be fixed now. If not, then please re-open.
