### ISSUE TITLE
GroundDB on Meteor Unable to handle file size >= 5MB

### ISSUE THREAD

**Issue by summer0nguyen** [Meteor-Community-Packages/ground-db#197]
Hello,
I'm using GroundDB for my Meteor project.
Everything works fine with small data . 

The problem occurs when I upload a file with size >= 5MB  in an object with a base64 field , something like : 
![image](https://cloud.githubusercontent.com/assets/6456947/26590780/be89ea5a-4585-11e7-82ef-86c3ab783b19.png)

This object disappears without any notification . 

I think that It was caused by Storage Limit 5MB . 
I found that GroundDB also supports indexDB which is stored in temporary storage that can be increased . 

Could you tell me how can I use IndexDB for this purpose. 
Thank you

**Comment by raix** [comment]
using v2 it should actually select the best storage possible on the client - you can inspect the storage in devtools ressources. You might also be able to inspect the `storage` entity on a ground db instance to see what type of storage it's using. (on cordova I tried to have it use sqlite but the plugin did not work accordingly)

**Comment by summer0nguyen** [comment]
Dear @raix ,
Thank you for your reply. 

Acording to : https://atmospherejs.com/ground/db , 

![image](https://cloud.githubusercontent.com/assets/6456947/26595759/b0590f90-4596-11e7-91b9-91c1f633da90.png)


What do you mean v2 means in these above versions :D 
Thank you

**Comment by raix** [comment]
you can fix the version to `2.0.0-rc.7` thats the latest - but it's different from 0.3 in several ways (hopefully for the better - I'll see if I get some time soon to get it out of rc)

**Comment by summer0nguyen** [comment]
Dear @raix ,
I'm appreciated .
