### ISSUE TITLE
.observeSource is not a function

### ISSUE THREAD

**Issue by thijssmudde** [Meteor-Community-Packages/ground-db#200]
offlineroutes.js:5 Uncaught TypeError: routesoffline.observeSource is not a function

```
import '/both/collections.js';

var routesoffline = new Ground.Collection('RoutesOffline');

routesoffline.observeSource(Routes.find());
```

collections.js
`Routes = new Mongo.Collection("routes");`

**Comment by 300mice** [comment]
Hi!
If you are still having this issue I think I managed to solve it. I actually encountered it about the same time you posted :D
Now I am no expert in any of this but I think if you downloaded it using 
    meteor add ground:db
The version on Atmosphere is actually outdated, you need to instead clone the version on Git Hub into your /packages folder and then do the 
    meteor add ground:db
and it should update to the latest version..
Doing this solved my issue, sorry if it doesn't help.

**Comment by fullhdpixel** [comment]
Yes that works. I'll leave this open so other people can use your guide. Thanks

**Comment by lucfranken** [comment]
The current version on Atmosphere returns ground:db@2.0.0 so this issue seems solved. Tested on Meteor 1.6
