### ISSUE TITLE
storage data is wipped if app is killed and reopen

### ISSUE THREAD

**Issue by salmanhasni** [Meteor-Community-Packages/ground-db#220]
if app is killed and reopen the data is no longer available to be used in app

This is happening due to the issue that meteor when upgraded from version 1 to 2, the mini mingo cursor storage `_docs` is now `IdMap` ( wrapper on map datastructure ) rather the a plain javascript object, therefore where ever in the library the data is loaded in the client side collection as ` this._collection._docs._map[doc._id] = ...` is only added the data as dictionary in the object rather than loaded the documents in collection to be fetched later from mini mongo

**To Reproduce**

1. Open the app
2. Save data in ground db legacy 
3. close the app
4. open the app, data will not be there on ui ( or in mini mongo collection) but its available in indexdb

_I am assuming the fix will be relativility easy. We are using this package to make app content available offline, therefore we need to resolve it asap. I am going to fix it locally - I can also create PR for it, feel free to review it._

**Comment by StorytellerCZ** [comment]
Released in v2.2.1
