### ISSUE TITLE
Limit ground db storing data as per query with LIFO method

### ISSUE THREAD

**Issue by nicolsondsouza** [Meteor-Community-Packages/ground-db#23]
Hi, I want to do it by my own but not sure where to start with,
I have a mobile application and cannot accept the processing of 200 data in each collection, I just need 16 data per collection with LIFO method, 
I saw your code but seems like after many days it's not easy to get in,
but if you explain a bit will help me out,

Thanks
Nicolson Dsouza

**Comment by mitiaptest** [comment]
Hi Raix,

We are facing same problem Do you have any idea how to fetch number of records only.( with limit and skip).
If we are going to use limit query "Match error: Failed Match.OneOf or Match.Optional validation" 

Please help me on it.

Thanks,
Mit
