### ISSUE TITLE
Error "First argument to new Mongo.Collection..."

### ISSUE THREAD

**Issue by jadsonlourenco** [Meteor-Community-Packages/ground-db#67]
This is an interesting error that I received today, after I updated my projects.
I have two projects, both use the same argument to bring a Mongo.collection to work offline with this package.

the first project I have this:

```
Questions = new Mongo.Collection('questions');
Ground.Collection(Questions);
```

This works well, I get this collection from DDP, from second project.

But on second project I have this:

```
Faq = new Mongo.Collection('faq');
Ground.Collection(Faq);
```

In this case I have a remote database, and not work, show this error: **Error: First argument to new Mongo.Collection must be a string or null**.
But as we can see is the same way to do the Collection call, why not work on second case? I don't know yet.

I appreciate the work you for it, and thanks for the reply to help me.

**Comment by miri-am** [comment]
I still get exactly this error when I try to ground Meteor.users: Error: First argument to new Mongo.Collection must be a string or null

**Comment by raix** [comment]
so you are using grounddb to ground the users collection on the client only or also the server?
grounding the Meteor.users collection should work - it seems as if the instance test should be optimized

**Comment by miri-am** [comment]
if(Meteor.isClient){
	    Ground.Collection(Meteor.users);	
    }
Error: First argument to new Mongo.Collection must be a string or null

**Comment by raix** [comment]
Question is if Meteor.users is an instance of Mongo.Collection or Meteor.Collection

**Comment by miri-am** [comment]
is there something I can check? Running Meteor.users in the console says it is a Mongo.Collection

**Comment by Kestanous** [comment]
:+1: to the Meteor.users issue. Was this ever resolved?
